### PR TITLE
Dependabot config update

### PR DESCRIPTION
**Pull request by DaisyDomergue**

### CODE REVIEW

**Comment by kare** [comment]
@DaisyDomergue Changes in file `.github/workflows/ci-cd.yaml` belong to PR #195

**Comment by kare** [comment]
@DaisyDomergue 
1. You can extract patches as files with command: `git format-patch HEAD~4`
2. And apply files to another Git branch with: `git am 0001-*.patch`

**Comment by DaisyDomergue** [comment]
Managed to change it with a rebase hope that is okay

**Review by kare — APPROVED** [review]
LGTM

**Pull request merged**
